server:
  http_listen_port: 3101
  grpc_listen_port: 9096

clients:
  - url: http://loki:3100/api/prom/push   # Loki endpoint URL

positions:
  filename: /tmp/positions.yaml   # Make sure this path is writable inside the container

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log
